<a href="https://colab.research.google.com/github/LeopoldBloom2K/demo1/blob/master/pandas_practice_blank.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐼 Kaggle Pandas Course — 빈칸 채우기 실습
> **사용법**: `# TODO` 부분을 직접 코드로 채운 뒤 셀을 실행하세요.  
> 힌트는 바로 아래 주석에 있습니다. 막히면 참고하세요!

---

## ⚙️ 사전 준비 — 라이브러리 & 데이터 생성
> 이 셀은 수정하지 말고 그대로 실행하세요.

In [8]:
import pandas as pd
import numpy as np

np.random.seed(42)

orders = pd.DataFrame({
    'order_id': range(1001, 1021),
    'customer_name': ['김민준','이서연','박도윤','최서현','정시우','강예린','윤지호','임나은','장하준','오수아',
                      '한지민','신이준','오하은','서준혁','권다인','황민서','안지아','배도현','조하린','윤시현'],
    'category': ['전자기기','의류','식품','전자기기','의류','식품','전자기기','의류','식품','전자기기',
                 '의류','식품','전자기기','의류','식품','전자기기','의류','식품','전자기기','의류'],
    'product': ['노트북','티셔츠','사과','스마트폰','청바지','과자','태블릿','원피스','쌀','이어폰',
                '코트','양말','스마트워치','후드티','라면','키보드','스커트','초콜릿','마우스','가방'],
    'price': [1200000, 35000, 15000, 850000, 65000, 3500, 450000, 78000, 25000, 89000,
              320000, 5000, 280000, 45000, 4500, 95000, 55000, 2500, 38000, 120000],
    'quantity': [1,2,5,1,3,10,1,1,3,2,1,5,1,2,8,1,2,4,1,1],
    'region': ['서울','부산','서울','대구','부산','서울','인천','서울','부산','대구',
               '서울','인천','부산','서울','대구','인천','서울','부산','대구','서울'],
    'order_date': pd.date_range('2024-01-05', periods=20, freq='5D').strftime('%Y-%m-%d').tolist(),
    'rating': [4.5, 3.8, 4.2, 4.9, 3.5, None, 4.1, 4.6, None, 4.3,
               3.9, 4.0, 4.7, 3.6, None, 4.8, 4.2, 3.7, 4.5, 4.1],
    'is_returned': [False,False,False,False,True,False,False,True,False,False,
                    False,False,False,True,False,False,False,False,True,False]
})

customers = pd.DataFrame({
    'customer_name': ['김민준','이서연','박도윤','최서현','정시우','강예린','윤지호','임나은','장하준','오수아',
                      '한지민','신이준','오하은','서준혁','권다인','황민서','안지아','배도현','조하린','윤시현'],
    'age': [28,35,22,41,29,33,26,38,45,31,27,39,24,52,36,29,43,31,28,37],
    'membership': ['골드','실버','브론즈','골드','실버','브론즈','골드','골드','실버','브론즈',
                   '골드','실버','브론즈','골드','실버','골드','브론즈','실버','골드','실버']
})

orders.to_csv('orders.csv', index=False, encoding='utf-8-sig')
customers.to_csv('customers.csv', index=False, encoding='utf-8-sig')
print('✅ 데이터 준비 완료!')
print(f'   orders : {orders.shape}  |  customers : {customers.shape}')

✅ 데이터 준비 완료!
   orders : (20, 10)  |  customers : (20, 3)

---
## 📖 Chapter 1 — Creating, Reading and Writing
**목표**: CSV 읽기·저장, DataFrame/Series 생성 마스터하기

In [14]:
# ─────────────────────────────────────────
# Q1. orders.csv를 읽어서 df에 저장하세요.
#     조건 1) order_id 컬럼을 인덱스로 지정
#     조건 2) order_date 컬럼을 날짜 타입으로 파싱
# ─────────────────────────────────────────
# 힌트: pd.read_csv('파일명', index_col=___, parse_dates=[___])

df = pd.read_csv('orders.csv', index_col='order_id', parse_dates=['order_date'])

print('[Q1 결과] 상위 3행')
print(df.head(3))
print(f'\norder_date dtype: {df["order_date"].dtype}')  # datetime64 이어야 정답!

[Q1 결과] 상위 3행
         customer_name category product    price  quantity region order_date  \
order_id
1001               김민준     전자기기     노트북  1200000         1     서울 2024-01-05
1002               이서연       의류     티셔츠    35000         2     부산 2024-01-10
1003               박도윤       식품      사과    15000         5     서울 2024-01-15

          rating  is_returned
order_id
1001         4.5        False
1002         3.8        False
1003         4.2        False

order_date dtype: datetime64[ns]

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [15]:
# ─────────────────────────────────────────
# Q2. 아래 데이터로 fruits라는 Series를 만드세요.
#     값: [500, 1200, 300, 800]
#     인덱스: ['사과', '수박', '바나나', '포도']
# ─────────────────────────────────────────
# 힌트: pd.Series([값 리스트], index=[인덱스 리스트], name='시리즈 이름')

fruits = pd.Series([500, 1200, 300, 800], index=['사과', '수박', '바나나', '포도'], name='fruits')

print('[Q2 결과]')
print(fruits)

[Q2 결과]
사과      500
수박     1200
바나나     300
포도      800
Name: fruits, dtype: int64

In [16]:
# ─────────────────────────────────────────
# Q3. df를 'orders_backup.csv'로 저장하세요.
#     조건) 인덱스(order_id)도 함께 저장
# ─────────────────────────────────────────
# 힌트: df.to_csv('파일명')  ← index 기본값이 True임

df.to_csv('orders_backup.csv', index=True)

print('[Q3 결과] orders_backup.csv 저장 완료')

# 저장 확인: 다시 읽어서 shape 출력
check = pd.read_csv('orders_backup.csv', index_col='order_id')
print(f'저장된 파일 shape: {check.shape}')  # (20, 9) 이어야 정답!

[Q3 결과] orders_backup.csv 저장 완료
저장된 파일 shape: (20, 9)

---
## 🔍 Chapter 2 — Indexing, Selecting & Assigning
**목표**: iloc / loc / 조건부 선택 자유자재로 다루기

In [22]:
# ─────────────────────────────────────────
# Q1. iloc으로 df의 마지막 3행, 처음 4개 컬럼을 선택하세요.
# ─────────────────────────────────────────
# 힌트: df.iloc[시작:끝, 시작:끝]  ← 음수 인덱스(-3) 사용 가능

result = df.iloc[-3, :4]

print('[Q1 결과]')
print(result)

[Q1 결과]
customer_name     배도현
category           식품
product           초콜릿
price            2500
Name: 1018, dtype: object

In [19]:
# ─────────────────────────────────────────
# Q2. loc으로 order_id 1005~1008번의
#     customer_name, product, price 컬럼만 선택하세요.
# ─────────────────────────────────────────
# 힌트: df.loc[시작id:끝id, ['컬럼1', '컬럼2', '컬럼3']]
#       ★ loc은 끝 레이블 포함!

result = df.loc[1005:1008, ['customer_name', 'product', 'price']]

print('[Q2 결과]')
print(result)

[Q2 결과]
         customer_name product   price
order_id
1005               정시우     청바지   65000
1006               강예린      과자    3500
1007               윤지호     태블릿  450000
1008               임나은     원피스   78000

In [26]:
# ─────────────────────────────────────────
# Q3. 아래 두 조건을 모두 만족하는 행을 필터링하세요.
#     조건 1) category가 '전자기기'
#     조건 2) rating이 4.5 이상
#     출력: product, price, rating 컬럼만
# ─────────────────────────────────────────
# 힌트: df.loc[(조건1) & (조건2), ['컬럼'...]]
#       ★ 각 조건은 반드시 ()로 감쌀 것!

result = df.loc[(df['category'] == '전자기기') & (df['rating'] >= 4.5), ['product', 'price', 'rating']]

print('[Q3 결과]')
print(result)

[Q3 결과]
         product    price  rating
order_id
1001         노트북  1200000     4.5
1004        스마트폰   850000     4.9
1013       스마트워치   280000     4.7
1016         키보드    95000     4.8
1019         마우스    38000     4.5

In [27]:
# ─────────────────────────────────────────
# Q4. df에 'total_amount' 컬럼을 추가하세요.
#     계산식: price × quantity
# ─────────────────────────────────────────
# 힌트: df['새컬럼명'] = df['컬럼A'] * df['컬럼B']

df['total_amount'] = df['price'] * df['quantity']

print('[Q4 결과] total_amount 상위 5행')
print(df[['product', 'price', 'quantity', 'total_amount']].head(5))

[Q4 결과] total_amount 상위 5행
         product    price  quantity  total_amount
order_id
1001         노트북  1200000         1       1200000
1002         티셔츠    35000         2         70000
1003          사과    15000         5         75000
1004        스마트폰   850000         1        850000
1005         청바지    65000         3        195000

---
## 📊 Chapter 3 — Summary Functions and Maps
**목표**: 데이터 요약 & map/apply로 전체 변환하기

In [29]:
# ─────────────────────────────────────────
# Q1. price 컬럼의 요약 통계를 출력하세요.
#     추가로 category 컬럼의 값별 개수도 출력하세요.
# ─────────────────────────────────────────
# 힌트: df['컬럼'].describe()  /  df['컬럼'].value_counts()

print('[Q1-1] price 요약 통계')
df['price'].describe()

print('\n[Q1-2] category 값별 개수')
df['category'].value_counts()

[Q1-1] price 요약 통계

[Q1-2] category 값별 개수

category
전자기기    7
의류      7
식품      6
Name: count, dtype: int64

In [30]:
# ─────────────────────────────────────────
# Q2. map을 사용해 price를 만원 단위로 변환하여
#     'price_만원' 컬럼을 만드세요.
#     (소수점 1자리, 예: 1200000 → 120.0)
# ─────────────────────────────────────────
# 힌트: df['컬럼'].map(lambda x: round(x / 10000, 1))

df['price_만원'] = df['price'].map(lambda x: round(x / 10000, 1))

print('[Q2 결과]')
print(df[['product', 'price', 'price_만원']].head(5))

[Q2 결과]
         product    price  price_만원
order_id
1001         노트북  1200000     120.0
1002         티셔츠    35000       3.5
1003          사과    15000       1.5
1004        스마트폰   850000      85.0
1005         청바지    65000       6.5

In [37]:
# ─────────────────────────────────────────
# Q3. apply를 사용해 각 행의 total_amount를 기준으로
#     'vip' 컬럼을 만드세요.
#     조건: total_amount >= 200000 → True, 미만 → False
# ─────────────────────────────────────────
# 힌트: df.apply(lambda row: ___, axis=1)
#       row['컬럼명'] 으로 해당 행의 값에 접근

df['vip'] = df.apply(lambda row: row['total_amount'] >= 200000, axis=1)

print('[Q3 결과]')
print(df[['product', 'total_amount', 'vip']].head(8))

[Q3 결과]
         product  total_amount    vip
order_id
1001         노트북       1200000   True
1002         티셔츠         70000  False
1003          사과         75000  False
1004        스마트폰        850000   True
1005         청바지        195000  False
1006          과자         35000  False
1007         태블릿        450000   True
1008         원피스         78000  False

---
## 📦 Chapter 4 — Grouping and Sorting
**목표**: groupby + agg 조합 & 정렬 마스터하기

In [42]:
# ─────────────────────────────────────────
# Q1. region(지역)별로 총 주문건수와 총매출(total_amount 합계)을
#     Named Aggregation 방식으로 구하세요.
# ─────────────────────────────────────────
# 힌트: df.groupby('기준컬럼').agg(
#           결과컬럼명=('원본컬럼', '집계함수'),
#           결과컬럼명=('원본컬럼', '집계함수')
#       ).reset_index()
#  집계함수: 'count' / 'sum' / 'mean' / 'min' / 'max'

reset = df.groupby('region').agg(
        주문건수 = ('price', 'count'),
        매출 = ('total_amount', 'sum')
    ).reset_index()

print('[Q1 결과]')
print(result)

[Q1 결과]
         product    price  rating
order_id
1001         노트북  1200000     4.5
1004        스마트폰   850000     4.9
1013       스마트워치   280000     4.7
1016         키보드    95000     4.8
1019         마우스    38000     4.5

In [44]:
# ─────────────────────────────────────────
# Q2. category + region 두 기준으로 그룹화하여
#     평균 rating을 소수점 2자리로 구하세요.
# ─────────────────────────────────────────
# 힌트: df.groupby([___, ___])['rating'].mean().round(2)

result = df.groupby(['category', 'region'])['rating'].mean().round(2)

print('[Q2 결과]')
print(result)

[Q2 결과]
category  region
식품        대구         NaN
          부산        3.70
          서울        4.20
          인천        4.00
의류        부산        3.65
          서울        4.08
전자기기      대구        4.57
          부산        4.70
          서울        4.50
          인천        4.45
Name: rating, dtype: float64

In [49]:
# ─────────────────────────────────────────
# Q3. total_amount 기준 내림차순으로 정렬하되,
#     total_amount가 같으면 price 오름차순으로 정렬하세요.
#     product, price, total_amount 컬럼만 상위 5개 출력
# ─────────────────────────────────────────
# 힌트: df.sort_values(by=[___], ascending=[___])
#       다중 정렬: by 리스트, ascending 리스트로 각각 지정

result = df.sort_values(by=['total_amount'], ascending=False)

print('[Q3 결과]')
print(result)

[Q3 결과]
         customer_name category product    price  quantity region order_date  \
order_id
1001               김민준     전자기기     노트북  1200000         1     서울 2024-01-05
1004               최서현     전자기기    스마트폰   850000         1     대구 2024-01-20
1007               윤지호     전자기기     태블릿   450000         1     인천 2024-02-04
1011               한지민       의류      코트   320000         1     서울 2024-02-24
1013               오하은     전자기기   스마트워치   280000         1     부산 2024-03-05
1005               정시우       의류     청바지    65000         3     부산 2024-01-25
1010               오수아     전자기기     이어폰    89000         2     대구 2024-02-19
1020               윤시현       의류      가방   120000         1     서울 2024-04-09
1017               안지아       의류     스커트    55000         2     서울 2024-03-25
1016               황민서     전자기기     키보드    95000         1     인천 2024-03-20
1014               서준혁       의류     후드티    45000         2     서울 2024-03-10
1008               임나은       의류     원피스    78000         1     서울 2024-02-09
1009               장하준       식품       쌀    25000         3     부산 2024-02-14
1003               박도윤       식품      사과    15000         5     서울 2024-01-15
1002               이서연       의류     티셔츠    35000         2     부산 2024-01-10
1019               조하린     전자기기     마우스    38000         1     대구 2024-04-04
1015               권다인       식품      라면     4500         8     대구 2024-03-15
1006               강예린       식품      과자     3500        10     서울 2024-01-30
1012               신이준       식품      양말     5000         5     인천 2024-02-29
1018               배도현       식품     초콜릿     2500         4     부산 2024-03-30

          rating  is_returned  total_amount  price_만원    vip
order_id
1001         4.5        False       1200000     120.0   True
1004         4.9        False        850000      85.0   True
1007         4.1        False        450000      45.0   True
1011         3.9        False        320000      32.0   True
1013         4.7        False        280000      28.0   True
1005         3.5         True        195000       6.5  False
1010         4.3        False        178000       8.9  False
1020         4.1        False        120000      12.0  False
1017         4.2        False        110000       5.5  False
1016         4.8        False         95000       9.5  False
1014         3.6         True         90000       4.5  False
1008         4.6         True         78000       7.8  False
1009         NaN        False         75000       2.5  False
1003         4.2        False         75000       1.5  False
1002         3.8        False         70000       3.5  False
1019         4.5         True         38000       3.8  False
1015         NaN        False         36000       0.5  False
1006         NaN        False         35000       0.3  False
1012         4.0        False         25000       0.5  False
1018         3.7        False         10000       0.2  False

---
## 🧹 Chapter 5 — Data Types and Missing Values
**목표**: 타입 변환 & 결측치 탐지·처리 완전 정복

In [53]:
# ─────────────────────────────────────────
# Q1. df 전체 컬럼의 타입을 확인하고,
#     결측치가 있는 컬럼과 그 개수를 출력하세요.
# ─────────────────────────────────────────
# 힌트: df.dtypes
#       df.isnull().sum()  ← 0보다 큰 것만 필터: [df.isnull().sum() > 0]

print('[Q1-1] 컬럼별 데이터 타입')
df.dtypes

print('\n[Q1-2] 결측치 있는 컬럼')
df.isnull().sum() > 0

[Q1-1] 컬럼별 데이터 타입

[Q1-2] 결측치 있는 컬럼

customer_name    False
category         False
product          False
price            False
quantity         False
region           False
order_date       False
rating            True
is_returned      False
total_amount     False
price_만원         False
vip              False
dtype: bool

In [54]:
# ─────────────────────────────────────────
# Q2. rating 컬럼의 결측치를 중앙값(median)으로 채우세요.
#     채우기 전과 후의 결측치 개수를 각각 출력하세요.
# ─────────────────────────────────────────
# 힌트: df['컬럼'].isnull().sum()  ← 결측치 개수
#       df['컬럼'] = df['컬럼'].fillna(df['컬럼'].median())

print(f'[Q2] fillna 전 결측치 수: {df["rating"].isnull().sum()}')

df['rating'].isnull().sum()
df['rating'] = df['rating'].fillna(df['rating'].isnull().median())

print(f'[Q2] fillna 후 결측치 수: {df["rating"].isnull().sum()}')  # 0 이어야 정답!

[Q2] fillna 전 결측치 수: 3
[Q2] fillna 후 결측치 수: 0

In [57]:
# ─────────────────────────────────────────
# Q3-1. is_returned 컬럼을 bool에서 int64로 변환하여
#        'is_returned_int' 컬럼을 만드세요.
# Q3-2. region 컬럼에서 '서울'을 'SEOUL'로 일괄 치환하세요.
# ─────────────────────────────────────────
# 힌트 Q3-1: df['컬럼'].astype('타입문자열')  → 'int64'
# 힌트 Q3-2: df['컬럼'].replace('기존값', '바꿀값')

# Q3-1
df['is_returned_int'] = df['is_returned'].astype('int64')

# Q3-2
df['region'] = df['region'].replace('서울', 'SEOUL')

print('[Q3-1] bool → int 변환')
print(df[['is_returned', 'is_returned_int']].head(6))
print('\n[Q3-2] 서울 → SEOUL 치환')
print(df['region'].unique())

[Q3-1] bool → int 변환
          is_returned  is_returned_int
order_id
1001            False                0
1002            False                0
1003            False                0
1004            False                0
1005             True                1
1006            False                0

[Q3-2] 서울 → SEOUL 치환
['SEOUL' '부산' '대구' '인천']

---
## 🔗 Chapter 6 — Combining
**목표**: concat / merge / join으로 데이터 결합하기

In [58]:
# ─────────────────────────────────────────
# Q1. df를 절반으로 나눈 뒤 concat으로 다시 합치세요.
#     합친 결과의 shape을 출력해 원본과 같은지 확인하세요.
# ─────────────────────────────────────────
# 힌트: df.iloc[:10]  /  df.iloc[10:]
#       pd.concat([df1, df2], axis=0)

first_half  = df.iloc[:10]
second_half = df.iloc[10:]
combined    = pd.concat([first_half, second_half], axis=0)

print(f'[Q1] 원본 shape: {df.shape}  |  합친 shape: {combined.shape}')  # 동일해야 정답!

[Q1] 원본 shape: (20, 13)  |  합친 shape: (20, 13)

In [61]:
# ─────────────────────────────────────────
# Q2. df(주문)와 customers(고객 정보)를
#     'customer_name'을 기준으로 LEFT JOIN 하세요.
#     결과에서 customer_name, product, price, age, membership 컬럼만 출력
# ─────────────────────────────────────────
# 힌트: df.reset_index().merge(other_df, on='공통컬럼', how='___')
#       LEFT JOIN → how='left'

merged = df.reset_index().merge(customers, on='customer_name', how='left')

print('[Q2 결과] 상위 5행')
print(merged[['customer_name', 'product', 'price', 'age', 'membership']].head(5))

[Q2 결과] 상위 5행
  customer_name product    price  age membership
0           김민준     노트북  1200000   28         골드
1           이서연     티셔츠    35000   35         실버
2           박도윤      사과    15000   22        브론즈
3           최서현    스마트폰   850000   41         골드
4           정시우     청바지    65000   29         실버

In [62]:
# ─────────────────────────────────────────
# Q3. merge된 데이터에서 membership 등급별
#     평균 구매금액(total_amount)을 내림차순으로 출력하세요.
#     (소수점 없이 정수로 반올림)
# ─────────────────────────────────────────
# 힌트: merged.groupby('___')['___'].mean()
#              .sort_values(ascending=False).round(0)

result = merged.groupby('membership')['total_amount'].mean().sort_values(ascending=False).round(0)

print('[Q3 결과] 멤버십 등급별 평균 구매금액')
print(result)

[Q3 결과] 멤버십 등급별 평균 구매금액
membership
골드     390125.0
브론즈    135600.0
실버      75857.0
Name: total_amount, dtype: float64

---
## ✅ 최종 점검 — 전체 답 확인
> 모든 문제를 풀었다면 아래 셀을 실행해 정답과 비교해 보세요!

In [63]:
print('=' * 55)
print('           🎯 정답 출력 (채점용)')
print('=' * 55)

# --- 사전 준비 (정답 계산용) ---
_df = pd.read_csv('orders.csv', index_col='order_id', parse_dates=['order_date'])
_df['total_amount'] = _df['price'] * _df['quantity']

print('\n[Ch1-Q1] order_date dtype:', _df['order_date'].dtype)
print('[Ch1-Q2] fruits Series:')
print(pd.Series([500, 1200, 300, 800], index=['사과','수박','바나나','포도'], name='과일가격'))

print('\n[Ch2-Q1] iloc 마지막 3행, 처음 4컬럼:')
print(_df.iloc[-3:, :4])
print('\n[Ch2-Q3] 전자기기 & rating≥4.5:')
print(_df.loc[(_df['category']=='전자기기') & (_df['rating']>=4.5), ['product','price','rating']])

print('\n[Ch3-Q2] price_만원 상위 5행:')
_df['price_만원'] = _df['price'].map(lambda x: round(x/10000, 1))
print(_df[['product','price','price_만원']].head(5))

print('\n[Ch4-Q1] region별 주문건수 & 총매출:')
print(_df.groupby('region').agg(주문건수=('price','count'), 총매출=('total_amount','sum')).reset_index())

print('\n[Ch5-Q2] fillna 후 결측치 수:', _df['rating'].fillna(_df['rating'].median()).isnull().sum())

print('\n[Ch6-Q3] 멤버십별 평균 구매금액:')
_m = _df.reset_index().merge(customers, on='customer_name', how='left')
print(_m.groupby('membership')['total_amount'].mean().sort_values(ascending=False).round(0))

print('\n' + '=' * 55)
print('정답과 비교 완료! 틀린 부분은 힌트를 다시 확인하세요 💪')
print('=' * 55)

=======================================================
           🎯 정답 출력 (채점용)
=======================================================

[Ch1-Q1] order_date dtype: datetime64[ns]
[Ch1-Q2] fruits Series:
사과      500
수박     1200
바나나     300
포도      800
Name: 과일가격, dtype: int64

[Ch2-Q1] iloc 마지막 3행, 처음 4컬럼:
         customer_name category product   price
order_id
1018               배도현       식품     초콜릿    2500
1019               조하린     전자기기     마우스   38000
1020               윤시현       의류      가방  120000

[Ch2-Q3] 전자기기 & rating≥4.5:
         product    price  rating
order_id
1001         노트북  1200000     4.5
1004        스마트폰   850000     4.9
1013       스마트워치   280000     4.7
1016         키보드    95000     4.8
1019         마우스    38000     4.5

[Ch3-Q2] price_만원 상위 5행:
         product    price  price_만원
order_id
1001         노트북  1200000     120.0
1002         티셔츠    35000       3.5
1003          사과    15000       1.5
1004        스마트폰   850000      85.0
1005         청바지    65000       6.5

[Ch4-Q1] region별 주문건수 & 총매출:
  region  주문건수      총매출
0     대구     4  1102000
1     부산     5   630000
2     서울     8  2028000
3     인천     3   570000

[Ch5-Q2] fillna 후 결측치 수: 0

[Ch6-Q3] 멤버십별 평균 구매금액:
membership
골드     390125.0
브론즈    135600.0
실버      75857.0
Name: total_amount, dtype: float64

=======================================================
정답과 비교 완료! 틀린 부분은 힌트를 다시 확인하세요 💪
=======================================================